name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # https://github.com/lowlighter/metrics/blob/latest/source/plugins/core/README.md
          user: 2shiori17
          base: header
          config_timezone: Asia/Tokyo
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/topics/README.md
          plugin_topics: yes
          plugin_topics_mode: icons
